// lib/core/pdf_report_service.dart
// English-only attendance report (Arabic support removed).
import 'dart:io';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:path_provider/path_provider.dart';
import 'package:open_file/open_file.dart';
import 'package:flutter/material.dart';

class PdfReportService {
  static Future<bool> generateAndOpen(BuildContext context, Map<String, dynamic> report) async {
    try {
      final pdf = pw.Document();

      final subjectName = report['subjectName'] ?? 'Unknown Subject';
      final subjectCode = report['subjectCode'] ?? '';
      final doctorName = report['doctorName'] ?? '';
      // Match the website fields: startTime / endTime. createdAt is the
      // *report-saved* timestamp and must NOT be used as session start.
      final startTime = (report['startTime'] ??
              report['start_time'] ??
              report['startedAt'] ??
              '')
          .toString();
      final endTime = (report['endTime'] ??
              report['end_time'] ??
              report['endedAt'] ??
              report['ended_at'] ??
              report['createdAt'] ??
              '')
          .toString();
      final createdAt = startTime.isNotEmpty ? startTime : endTime;
      final endedAt = endTime;
      final totalStudents = report['totalStudents'] ?? 0;
      final presentCount = report['presentCount'] ?? 0;
      final pendingCount = report['pendingCount'] ?? 0;
      final absentCount = totalStudents - presentCount - pendingCount;
      final students = (report['students'] as List?)?.cast<Map<String, dynamic>>() ?? [];
      final level = report['level'] ?? '';
      final department = report['department'] ?? '';
      final attendanceRate = totalStudents > 0 ? (presentCount / totalStudents * 100).toStringAsFixed(1) : '0';

      pdf.addPage(pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(40),
        header: (ctx) => _header(subjectName, subjectCode, doctorName, _dateOnly(createdAt)),
        footer: (ctx) => pw.Row(
          mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
          children: [
            pw.Text('Generated by Traxa',
              style: pw.TextStyle(fontSize: 8, color: PdfColors.grey500)),
            pw.Text('Page ${ctx.pageNumber} of ${ctx.pagesCount}',
              style: pw.TextStyle(fontSize: 8, color: PdfColors.grey500)),
          ],
        ),
        build: (ctx) => [
          pw.SizedBox(height: 10),
          _summary(_time12(createdAt), _time12(endedAt), totalStudents, presentCount,
                   pendingCount, absentCount, attendanceRate, '$level', '$department'),
          pw.SizedBox(height: 20),
          pw.Text('Student Details',
            style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold)),
          pw.SizedBox(height: 8),
          _studentsTable(students),
        ],
      ));

      // Save
      final dir = await getApplicationDocumentsDirectory();
      final fileName = 'Report_${subjectName.replaceAll(' ', '_')}_${DateTime.now().millisecondsSinceEpoch}.pdf';
      final file = File('${dir.path}/$fileName');
      await file.writeAsBytes(await pdf.save());

      // Also save to Downloads if possible
      try {
        final dl = Directory('/storage/emulated/0/Download');
        if (await dl.exists()) { 
          await File('${dl.path}/$fileName').writeAsBytes(await pdf.save()); 
        }
      } catch (_) {}

      // Open
      final result = await OpenFile.open(file.path);
      if (result.type != ResultType.done && context.mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('PDF saved: ${file.path}'), 
            backgroundColor: Colors.green, 
            duration: const Duration(seconds: 5)
          )
        );
      }
      return true;
    } catch (e) {
      if (context.mounted) { 
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('PDF Error: $e'), backgroundColor: Colors.red)
        ); 
      }
      return false;
    }
  }

  static pw.Widget _header(String subject, String code, String doctor, String date) {
    return pw.Column(crossAxisAlignment: pw.CrossAxisAlignment.start, children: [
      pw.Row(mainAxisAlignment: pw.MainAxisAlignment.spaceBetween, children: [
        pw.Column(crossAxisAlignment: pw.CrossAxisAlignment.start, children: [
          pw.Text('Traxa Academic System',
            style: pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold,
                   color: PdfColor.fromHex('#8B5CF6'))),
          pw.Text('Attendance Report',
            style: pw.TextStyle(fontSize: 12, color: PdfColors.grey600)),
        ]),
        pw.Column(crossAxisAlignment: pw.CrossAxisAlignment.end, children: [
          pw.Text(date, style: const pw.TextStyle(fontSize: 11)),
          pw.Text('Dr. $doctor',
            style: pw.TextStyle(fontSize: 11, color: PdfColors.grey700)),
        ]),
      ]),
      pw.SizedBox(height: 8),
      pw.Divider(color: PdfColor.fromHex('#8B5CF6'), thickness: 2),
      pw.SizedBox(height: 8),
      pw.Text(subject, style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold)),
      if (code.isNotEmpty) pw.Text(code, style: pw.TextStyle(fontSize: 11, color: PdfColors.grey600)),
    ]);
  }

  static pw.Widget _summary(String start, String end, int total, int present, int pending,
      int absent, String rate, String level, String dept) {
    return pw.Container(
      padding: const pw.EdgeInsets.all(12),
      decoration: pw.BoxDecoration(border: pw.Border.all(color: PdfColors.grey300), borderRadius: pw.BorderRadius.circular(8)),
      child: pw.Column(children: [
        pw.Row(children: [
          _item('Start', start, null),
          _item('End', end, null),
          _item('Level', level, null),
          _item('Dept', dept, null)
        ]),
        pw.SizedBox(height: 10),
        pw.Divider(color: PdfColors.grey300),
        pw.SizedBox(height: 10),
        pw.Row(children: [
          _item('Total', '$total', PdfColors.blue),
          _item('Present', '$present', PdfColor.fromHex('#10B981')),
          _item('Pending', '$pending', PdfColor.fromHex('#F59E0B')),
          _item('Absent', '$absent', PdfColors.red),
          _item('Rate', '$rate%', PdfColor.fromHex('#8B5CF6')),
        ]),
      ]),
    );
  }

  static pw.Widget _item(String label, String value, PdfColor? color) {
    return pw.Expanded(child: pw.Column(children: [
      pw.Text(value,
        style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold,
               color: color ?? PdfColors.black)),
      pw.SizedBox(height: 2),
      pw.Text(label, style: pw.TextStyle(fontSize: 9, color: PdfColors.grey600)),
    ]));
  }

  static pw.Widget _studentsTable(List<Map<String, dynamic>> students) {
    if (students.isEmpty) {
      return pw.Text('No student data available',
        style: pw.TextStyle(color: PdfColors.grey500));
    }

    return pw.TableHelper.fromTextArray(
      headers: ['#', 'Student ID', 'Name', 'Status', 'Face', 'QR', 'Duration'],
      headerDecoration: pw.BoxDecoration(color: PdfColor.fromHex('#8B5CF6')),
      headerStyle: pw.TextStyle(fontSize: 9, fontWeight: pw.FontWeight.bold, color: PdfColors.white),
      cellStyle: const pw.TextStyle(fontSize: 8),
      cellAlignment: pw.Alignment.centerLeft,
      headerAlignment: pw.Alignment.centerLeft,
      columnWidths: {
        0: const pw.FixedColumnWidth(25),
        1: const pw.FixedColumnWidth(70),
        2: const pw.FlexColumnWidth(3),
        3: const pw.FixedColumnWidth(50),
        4: const pw.FixedColumnWidth(55),
        5: const pw.FixedColumnWidth(55),
        6: const pw.FixedColumnWidth(50),
      },
      cellDecoration: (index, data, rowNum) => pw.BoxDecoration(color: rowNum % 2 == 0 ? PdfColors.grey100 : PdfColors.white),
      data: students.asMap().entries.map((e) {
        final i = e.key;
        final s = e.value;
        final status = s['status'] ?? 'absent';
        final faceTime = _time12(s['face_detected_at'] ?? s['created_at'] ?? s['date'] ?? '');
        final qrTime = _time12(s['confirmed_at'] ?? s['qr_scanned_at'] ?? '');
        final duration = s['attendance_duration'] ?? '-';
        return [
          '${i + 1}',
          s['student_id_number']?.toString() ?? '',
          s['student_name'] ?? s['name'] ?? '',
          status == 'confirmed' ? 'Present' : status == 'pending' ? 'Pending' : 'Absent',
          faceTime,
          qrTime,
          duration.toString(),
        ];
      }).toList(),
    );
  }

  static String _time12(String iso) {
    if (iso.isEmpty) return '-';
    try {
      final dt = DateTime.parse(iso).toLocal();
      final h = dt.hour > 12 ? dt.hour - 12 : (dt.hour == 0 ? 12 : dt.hour);
      final ampm = dt.hour >= 12 ? 'PM' : 'AM';
      return '$h:${dt.minute.toString().padLeft(2, '0')} $ampm';
    } catch (_) { return '-'; }
  }

  static String _dateOnly(String iso) {
    try {
      final dt = DateTime.parse(iso).toLocal();
      return '${dt.day}/${dt.month}/${dt.year}';
    } catch (_) { return iso; }
  }
}