import 'dart:io';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:path_provider/path_provider.dart';
import 'package:open_file/open_file.dart';
import 'package:flutter/material.dart';

class PdfReportService {
  static Future<bool> generateAndOpen(BuildContext context, Map<String, dynamic> report) async {
    try {
      final pdf = pw.Document();

      final subjectName = report['subjectName'] ?? 'Unknown Subject';
      final subjectCode = report['subjectCode'] ?? '';
      final doctorName = report['doctorName'] ?? '';
      // Prefer the ISO copies (startTimeIso/endTimeIso) when present, then
      // fall back to the display strings. _time12 handles both formats.
      final startTime = (report['startTimeIso'] ??
              report['startTime'] ??
              report['start_time'] ??
              report['startedAt'] ??
              '')
          .toString();
      final endTime = (report['endTimeIso'] ??
              report['endTime'] ??
              report['end_time'] ??
              report['endedAt'] ??
              report['ended_at'] ??
              report['createdAt'] ??
              '')
          .toString();
      final createdAt = startTime.isNotEmpty ? startTime : endTime;
      final endedAt = endTime;
      final students0 = (report['students'] as List?) ?? [];
      final totalStudents = report['totalStudents'] ??
          report['total_students'] ??
          report['enrolled'] ??
          students0.length;
      final presentCount = report['presentCount'] ??
          report['present_count'] ??
          report['present'] ??
          students0.where((s) => s['status'] == 'confirmed').length;
      final pendingCount = report['pendingCount'] ??
          report['pending_count'] ??
          report['pending'] ??
          students0.where((s) => s['status'] == 'pending').length;
      final absentCount = totalStudents - presentCount - pendingCount;
      final students = (report['students'] as List?)?.cast<Map<String, dynamic>>() ?? [];
      final level = report['level'] ?? '';
      final department = report['department'] ?? '';
      final attendanceRate = totalStudents > 0 ? (presentCount / totalStudents * 100).toStringAsFixed(1) : '0';

      pdf.addPage(pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(40),
        header: (ctx) => _header(
            subjectName,
            subjectCode,
            doctorName,
            _dateOnly((report['createdAt'] ??
                    report['created_at'] ??
                    report['date'] ??
                    createdAt)
                .toString())),
        footer: (ctx) => pw.Row(
          mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
          children: [
            pw.Text('Generated by Traxa',
              style: pw.TextStyle(fontSize: 8, color: PdfColors.grey500)),
            pw.Text('Page ${ctx.pageNumber} of ${ctx.pagesCount}',
              style: pw.TextStyle(fontSize: 8, color: PdfColors.grey500)),
          ],
        ),
        build: (ctx) => [
          pw.SizedBox(height: 10),
          _summary(_time12(createdAt), _time12(endedAt), totalStudents, presentCount,
                   pendingCount, absentCount, attendanceRate, '$level', '$department'),
          pw.SizedBox(height: 20),
          pw.Text('Student Details',
            style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold)),
          pw.SizedBox(height: 8),
          _studentsTable(students),
        ],
      ));

      final dir = await getApplicationDocumentsDirectory();
      final fileName = 'Report_${subjectName.replaceAll(' ', '_')}_${DateTime.now().millisecondsSinceEpoch}.pdf';
      final file = File('${dir.path}/$fileName');
      await file.writeAsBytes(await pdf.save());

      try {
        final dl = Directory('/storage/emulated/0/Download');
        if (await dl.exists()) {
          await File('${dl.path}/$fileName').writeAsBytes(await pdf.save());
        }
      } catch (_) {}

      final result = await OpenFile.open(file.path);
      if (result.type != ResultType.done && context.mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('PDF saved: ${file.path}'),
            backgroundColor: Colors.green,
            duration: const Duration(seconds: 5)
          )
        );
      }
      return true;
    } catch (e) {
      if (context.mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('PDF Error: $e'), backgroundColor: Colors.red)
        );
      }
      return false;
    }
  }

  static pw.Widget _header(String subject, String code, String doctor, String date) {
    return pw.Column(crossAxisAlignment: pw.CrossAxisAlignment.start, children: [
      pw.Row(mainAxisAlignment: pw.MainAxisAlignment.spaceBetween, children: [
        pw.Column(crossAxisAlignment: pw.CrossAxisAlignment.start, children: [
          pw.Text('Traxa Academic System',
            style: pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold,
                   color: PdfColor.fromHex('#8B5CF6'))),
          pw.Text('Attendance Report',
            style: pw.TextStyle(fontSize: 12, color: PdfColors.grey600)),
        ]),
        pw.Column(crossAxisAlignment: pw.CrossAxisAlignment.end, children: [
          pw.Text(date, style: const pw.TextStyle(fontSize: 11)),
          pw.Text('Dr. $doctor',
            style: pw.TextStyle(fontSize: 11, color: PdfColors.grey700)),
        ]),
      ]),
      pw.SizedBox(height: 8),
      pw.Divider(color: PdfColor.fromHex('#8B5CF6'), thickness: 2),
      pw.SizedBox(height: 8),
      pw.Text(subject, style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold)),
      if (code.isNotEmpty) pw.Text(code, style: pw.TextStyle(fontSize: 11, color: PdfColors.grey600)),
    ]);
  }

  static pw.Widget _summary(String start, String end, int total, int present, int pending,
      int absent, String rate, String level, String dept) {
    return pw.Container(
      padding: const pw.EdgeInsets.all(12),
      decoration: pw.BoxDecoration(border: pw.Border.all(color: PdfColors.grey300), borderRadius: pw.BorderRadius.circular(8)),
      child: pw.Column(children: [
        pw.Row(children: [
          _item('Start', start, null),
          _item('End', end, null),
          _item('Level', level, null),
          _item('Dept', dept, null)
        ]),
        pw.SizedBox(height: 10),
        pw.Divider(color: PdfColors.grey300),
        pw.SizedBox(height: 10),
        pw.Row(children: [
          _item('Total', '$total', PdfColors.blue),
          _item('Present', '$present', PdfColor.fromHex('#10B981')),
          _item('Pending', '$pending', PdfColor.fromHex('#F59E0B')),
          _item('Absent', '$absent', PdfColors.red),
          _item('Rate', '$rate%', PdfColor.fromHex('#8B5CF6')),
        ]),
      ]),
    );
  }

  static pw.Widget _item(String label, String value, PdfColor? color) {
    return pw.Expanded(child: pw.Column(children: [
      pw.Text(value,
        style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold,
               color: color ?? PdfColors.black)),
      pw.SizedBox(height: 2),
      pw.Text(label, style: pw.TextStyle(fontSize: 9, color: PdfColors.grey600)),
    ]));
  }

  static pw.Widget _studentsTable(List<Map<String, dynamic>> students) {
    if (students.isEmpty) {
      return pw.Text('No student data available',
        style: pw.TextStyle(color: PdfColors.grey500));
    }

    const headers = ['#', 'Student ID', 'Name', 'Status', 'Face ID', 'QR', 'Duration'];
    final widths = {
      0: const pw.FixedColumnWidth(24),
      1: const pw.FixedColumnWidth(62),
      2: const pw.FlexColumnWidth(3),
      3: const pw.FixedColumnWidth(52),
      4: const pw.FixedColumnWidth(44),
      5: const pw.FixedColumnWidth(40),
      6: const pw.FixedColumnWidth(58),
    };

    pw.Widget cell(String text,
        {PdfColor? color,
        bool bold = false,
        pw.Alignment align = pw.Alignment.centerLeft}) {
      return pw.Container(
        alignment: align,
        padding: const pw.EdgeInsets.symmetric(horizontal: 4, vertical: 5),
        child: pw.Text(text,
            style: pw.TextStyle(
                fontSize: 8,
                color: color ?? PdfColors.black,
                fontWeight: bold ? pw.FontWeight.bold : pw.FontWeight.normal)),
      );
    }

    final rows = <pw.TableRow>[
      pw.TableRow(
        decoration: pw.BoxDecoration(color: PdfColor.fromHex('#8B5CF6')),
        children: headers
            .map((h) => pw.Container(
                  padding:
                      const pw.EdgeInsets.symmetric(horizontal: 4, vertical: 6),
                  child: pw.Text(h,
                      style: pw.TextStyle(
                          fontSize: 9,
                          fontWeight: pw.FontWeight.bold,
                          color: PdfColors.white)),
                ))
            .toList(),
      ),
    ];

    for (var i = 0; i < students.length; i++) {
      final s = students[i];
      final status = (s['status'] ?? 'absent').toString();

      // ── Face ID & QR: did the student actually do each step? ──────────
      final faceRaw = (s['face_detected_at'] ?? '').toString();
      final qrRaw = (s['qr_scanned_at'] ??
              (s['confirmedByQR'] == true ? (s['confirmed_at'] ?? '') : '') ??
              '')
          .toString();
      final hasFace = faceRaw.isNotEmpty;
      final hasQr = qrRaw.isNotEmpty || s['confirmedByQR'] == true;

      String duration = '-';
      if (hasFace && qrRaw.isNotEmpty) {
        final f = DateTime.tryParse(faceRaw);
        final q = DateTime.tryParse(qrRaw);
        if (f != null && q != null) {
          var diff = q.difference(f);
          if (diff.isNegative) diff = f.difference(q);
          final m = diff.inMinutes;
          final sec = diff.inSeconds % 60;
          duration = m > 0 ? '${m}m ${sec}s' : '${sec}s';
        }
      }

      // ── Status colour: green / yellow / red ───────────────────────────
      PdfColor statusBg;
      String statusLabel;
      if (status == 'confirmed') {
        statusBg = PdfColor.fromHex('#10B981');
        statusLabel = 'Present';
      } else if (status == 'pending') {
        statusBg = PdfColor.fromHex('#F59E0B');
        statusLabel = 'Pending';
      } else {
        statusBg = PdfColor.fromHex('#EF4444');
        statusLabel = 'Absent';
      }

      rows.add(pw.TableRow(
        decoration: pw.BoxDecoration(
            color: i % 2 == 0 ? PdfColors.grey100 : PdfColors.white),
        children: [
          cell('${i + 1}', align: pw.Alignment.center),
          cell((s['student_id_number'] ??
                  s['studentIdNumber'] ??
                  s['studentId'] ??
                  s['student_id'] ??
                  '')
              .toString()),
          cell((s['student_name'] ??
                  s['studentName'] ??
                  s['name'] ??
                  'Unknown')
              .toString()),
          pw.Container(
            alignment: pw.Alignment.center,
            color: statusBg,
            padding: const pw.EdgeInsets.symmetric(horizontal: 4, vertical: 5),
            child: pw.Text(statusLabel,
                style: pw.TextStyle(
                    fontSize: 8,
                    color: PdfColors.white,
                    fontWeight: pw.FontWeight.bold)),
          ),
          cell(hasFace ? 'Yes' : 'No',
              color: hasFace ? PdfColor.fromHex('#10B981') : PdfColors.red,
              bold: true,
              align: pw.Alignment.center),
          cell(hasQr ? 'Yes' : 'No',
              color: hasQr ? PdfColor.fromHex('#10B981') : PdfColors.red,
              bold: true,
              align: pw.Alignment.center),
          cell(duration, align: pw.Alignment.center),
        ],
      ));
    }

    return pw.Table(
      border: pw.TableBorder.all(color: PdfColors.grey300, width: 0.5),
      columnWidths: widths,
      children: rows,
    );
  }

  /// Formats a start/end time to a 12-hour clock string.
  /// Accepts either a full ISO datetime OR an already-formatted clock
  /// string (e.g. "8:05:23 PM", "20:16"). Website- and app-made reports
  /// store this field differently, so both must be handled.
  static String _time12(String raw) {
    if (raw.isEmpty) return '-';

    // Full ISO datetime.
    final dt = DateTime.tryParse(raw);
    if (dt != null) {
      final l = dt.toLocal();
      final h = l.hour > 12 ? l.hour - 12 : (l.hour == 0 ? 12 : l.hour);
      final ampm = l.hour >= 12 ? 'PM' : 'AM';
      return '$h:${l.minute.toString().padLeft(2, '0')} $ampm';
    }

    // Already a clock string ("HH:mm[:ss]" optionally with AM/PM).
    final m = RegExp(r'^(\d{1,2}):(\d{2})(?::\d{2})?\s*([AaPp][Mm])?$')
        .firstMatch(raw.trim());
    if (m != null) {
      var hour = int.parse(m.group(1)!);
      final minute = m.group(2)!;
      var ampm = m.group(3)?.toUpperCase();
      if (ampm == null) {
        ampm = hour >= 12 ? 'PM' : 'AM';
        if (hour > 12) hour -= 12;
        if (hour == 0) hour = 12;
      }
      return '$hour:$minute $ampm';
    }

    return raw;
  }

  static String _dateOnly(String iso) {
    try {
      final dt = DateTime.parse(iso).toLocal();
      return '${dt.day}/${dt.month}/${dt.year}';
    } catch (_) { return iso; }
  }
}
